services:
    sonarqube:
        image: sonarqube:latest
        ports:
            - "9000:9000"
    cli:
        image: sonarsource/sonar-scanner-cli
        environment:
            - SONAR_HOST_URL=http://sonarqube:9000
            - SONAR_TOKEN=sqp_1f6ade3ee9215a1ec43f95794f20a79c256cd68e
        volumes:
            - "./:/usr/src"