sonar.projectKey=fluffy-octo-sniffle
sonar.organization=turban-sizzle
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=test_app.py,test_service.py
sonar.sources=app.py,service.py