name: Build
on:
  push:
    branches:
      - main
jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: coverage
        run: pytest --cov . --cov-report xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}